"""Add email column to users

Revision ID: ba1622598c02
Revises: 
Create Date: 2026-03-31 03:06:44.724162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1622598c02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.drop_index(batch_op.f('emil'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('emil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emil', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('emil'), ['emil'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
